version: '3.8'

services:
  backend:
    build: .
    ports:
      - "7000:7000"
    depends_on:
      - db
    environment:
      - PORT=7000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=chatapp
      - JWT_SECRET=supersecretkey
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chatapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
